name: biogis
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.11.18=py310h89163eb_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - alabaster=1.0.0=pyhd8ed1ab_1
  - alsa-lib=1.2.14=hb9d3cd8_0
  - anndata=0.11.4=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - aom=3.9.1=hac33072_0
  - app-model=0.3.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - arpack=3.9.1=nompi_hf03ea27_102
  - asciitree=0.3.3=py_2
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attr=2.5.1=h166bdaf_1
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.8.6=hd08a7f5_4
  - aws-c-cal=0.8.7=h043a21b_0
  - aws-c-common=0.12.0=hb9d3cd8_0
  - aws-c-compression=0.3.1=h3870646_2
  - aws-c-event-stream=0.5.4=h04a3f94_2
  - aws-c-http=0.9.4=hb9b18c6_4
  - aws-c-io=0.17.0=h3dad3f2_6
  - aws-c-mqtt=0.12.2=h108da3e_2
  - aws-c-s3=0.7.13=h822ba82_2
  - aws-c-sdkutils=0.2.3=h3870646_2
  - aws-checksums=0.2.3=h3870646_2
  - aws-crt-cpp=0.31.0=h55f77e1_4
  - aws-sdk-cpp=1.11.510=h37a5c72_3
  - azure-core-cpp=1.14.0=h5cfcd09_0
  - azure-identity-cpp=1.10.0=h113e628_0
  - azure-storage-blobs-cpp=12.13.0=h3cf044e_1
  - azure-storage-common-cpp=12.8.0=h736e048_1
  - azure-storage-files-datalake-cpp=12.12.0=ha633028_1
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - blosc=1.21.6=he440d0b_1
  - bokeh=3.7.2=pyhd8ed1ab_1
  - branca=0.8.1=pyhd8ed1ab_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py310hf71b8c6_2
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - c-blosc2=2.15.2=h3122c55_1
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachey=0.2.1=pyh9f0ad1d_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py310h8deb56e_0
  - charls=2.4.2=h59595ed_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - click-default-group=1.2.4=pyhd8ed1ab_1
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorcet=3.1.0=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py310h3788b33_0
  - cpython=3.10.17=py310hd8ed1ab_0
  - cuda-crt-tools=12.8.93=ha770c72_3
  - cuda-cudart=12.8.90=h5888daf_1
  - cuda-cudart_linux-64=12.8.90=h3f2d84a_1
  - cuda-cuobjdump=12.8.90=hbd13f7d_1
  - cuda-cupti=12.8.90=h5888daf_1
  - cuda-nvcc-tools=12.8.93=he02047a_3
  - cuda-nvdisasm=12.8.90=hbd13f7d_1
  - cuda-nvrtc=12.8.93=h5888daf_1
  - cuda-nvtx=12.8.90=h5888daf_1
  - cuda-nvvm-tools=12.8.93=he02047a_3
  - cuda-version=12.8=h5d125a7_3
  - cudnn=9.8.0.87=h81d5506_1
  - cusparselt=0.7.0.0=hcd2ec93_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - cytoolz=1.0.1=py310ha75aee5_0
  - dask=2024.11.2=pyhff2d567_1
  - dask-core=2024.11.2=pyhff2d567_1
  - dask-expr=1.1.19=pyhd8ed1ab_0
  - dask-image=2024.5.3=pyhd8ed1ab_0
  - datashader=0.18.0=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.14=py310hf71b8c6_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - distributed=2024.11.2=pyhff2d567_1
  - docformatter=1.7.7=pyhd8ed1ab_0
  - docrep=0.3.2=pyh44b312d_0
  - docstring_parser=0.16=pyhd8ed1ab_0
  - docutils=0.21.2=pyhd8ed1ab_1
  - double-conversion=3.3.1=h5888daf_0
  - esda=2.7.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.0=h5888daf_0
  - fasteners=0.19=pyhd8ed1ab_1
  - fcsparser=0.2.8=pyhd8ed1ab_0
  - filelock=3.18.0=pyhd8ed1ab_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - folium=0.19.5=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=ha770c72_1
  - freetype-py=2.5.1=pyhd8ed1ab_1
  - freexl=2.0.0=h9dce30a_2
  - frozenlist=1.5.0=py310h89163eb_1
  - fsspec=2025.3.2=pyhd8ed1ab_0
  - geopandas=1.0.1=pyhd8ed1ab_3
  - geopandas-base=1.0.1=pyha770c72_3
  - geos=3.13.1=h97f6797_0
  - geotiff=1.7.4=h239500f_2
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310he8512ff_0
  - graphite2=1.3.13=h59595ed_1003
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.1.0=h3beb420_0
  - hdf5=1.14.3=nompi_h2d575fe_109
  - heapdict=1.0.1=pyhd8ed1ab_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - hsluv=5.0.4=pyhd8ed1ab_2
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - igraph=0.10.15=he44f51b_1
  - imagecodecs=2024.12.30=py310h78a9a29_0
  - imageio=2.37.0=pyhfb79c49_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - in-n-out=0.2.1=pyhd8ed1ab_1
  - inflect=7.5.0=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.36.0=pyh907856f_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - json-c=0.18=h6688a6e_0
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jxrlib=1.1=hd590300_3
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lamin_utils=0.14.0=pyhd8ed1ab_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - legacy-api-wrap=1.4.1=pyhd8ed1ab_0
  - leidenalg=0.10.2=py310hc6cd4ac_0
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libaec=1.1.3=h59595ed_0
  - libarchive=3.7.7=h75ea233_4
  - libarrow=19.0.1=h1938f28_3_cuda
  - libarrow-acero=19.0.1=hb826db4_3_cuda
  - libarrow-dataset=19.0.1=hb826db4_3_cuda
  - libarrow-substrait=19.0.1=hbf482d9_3_cuda
  - libavif16=1.2.1=hbb36593_2
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=31_he106b2a_openblas
  - libclang-cpp20.1=20.1.4=default_h1df26ce_0
  - libclang13=20.1.4=default_he06ed0a_0
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.8.4.1=h9ab20c4_1
  - libcudss0=0.4.0.2=he55f5cd_2
  - libcufft=11.3.3.83=h5888daf_1
  - libcufile=1.13.1.3=h628e99a_1
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.3.9.90=h9ab20c4_1
  - libcurl=8.13.0=h332b0f4_0
  - libcusolver=11.7.3.90=h9ab20c4_1
  - libcusparse=12.5.8.93=h5888daf_1
  - libdeflate=1.23=h86f0d12_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgdal-core=3.10.3=hab2de9c_5
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.1=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h767d61c_2
  - libgoogle-cloud=2.36.0=h2b5623c_0
  - libgoogle-cloud-storage=2.36.0=h0121fbd_0
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.67.1=h25350d4_2
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libhwy=1.2.0=hf40a0c7_0
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libjxl=0.11.1=h7b0646d_1
  - libkml=1.3.0=hf539b9f_1021
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - libleidenalg=0.11.1=h00ab1b0_0
  - libllvm20=20.1.4=he9d0ab4_0
  - liblzma=5.8.1=hb9d3cd8_0
  - libmagma=2.8.0=h566cb83_2
  - libnghttp2=1.64.0=h161d5f1_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libnvjitlink=12.8.93=h5888daf_1
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libopentelemetry-cpp=1.18.0=hfcad708_1
  - libopentelemetry-cpp-headers=1.18.0=ha770c72_1
  - libparquet=19.0.1=h3f30f2e_3_cuda
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.47=h943b412_0
  - libpq=17.4=h27ae623_1
  - libprotobuf=5.28.3=h6128344_1
  - libpysal=4.12.1=pyhd8ed1ab_1
  - libre2-11=2024.07.02=hbbce691_2
  - librttopo=1.1.0=hd718a1a_18
  - libsodium=1.0.20=h4ab18f5_0
  - libspatialite=5.1.0=he17ca71_14
  - libsqlite=3.49.1=hee588c1_2
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libsystemd0=257.4=h4e0b6ca_1
  - libthrift=0.21.0=h0e7cc3e_0
  - libtiff=4.7.0=hd9ff511_4
  - libtorch=2.6.0=cuda126_generic_h4a15719_200
  - libudev1=257.4=hbe16f8c_1
  - libutf8proc=2.10.0=h4c51ac1_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.50.0=hb9d3cd8_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.9.0=h65c71a3_0
  - libxml2=2.13.7=h4bc477f_1
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - libzopfli=1.0.3=h9c3ff4c_0
  - locket=1.0.0=pyhd8ed1ab_0
  - loguru=0.7.3=pyh707e725_0
  - lxml=5.4.0=py310h490dddc_0
  - lz4=4.3.3=py310h80b8a69_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - magicgui=0.10.0=pyhd8ed1ab_0
  - mapclassify=2.8.1=pyhd8ed1ab_1
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py310h89163eb_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - matplotlib-scalebar=0.9.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - minizip=4.0.9=h05a5f5f_0
  - more-itertools=10.7.0=pyhd8ed1ab_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.0=py310h3788b33_0
  - multidict=6.4.3=py310h89163eb_0
  - multipledispatch=0.6.0=pyhd8ed1ab_1
  - multiscale-spatial-image=2.0.2=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=9.2.0=h266115a_0
  - mysql-libs=9.2.0=he0572af_0
  - napari=0.6.0=pyhd8ed1ab_0
  - napari-base=0.6.0=pyh9208f05_0
  - napari-console=0.1.3=pyh73487a3_0
  - napari-matplotlib=3.0.0=pyh73487a3_0
  - napari-plugin-engine=0.2.0=pyha07c04f_3
  - napari-plugin-manager=0.1.6=pyha07c04f_0
  - napari-spatialdata=0.5.4.post0=pyh73487a3_0
  - napari-svg=0.2.1=pyha07c04f_0
  - narwhals=1.37.0=pyh29332c3_0
  - natsort=8.4.0=pyh29332c3_1
  - nccl=2.26.5.1=ha44e49d_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - nlohmann_json=3.12.0=h3f2d84a_0
  - nomkl=1.0=h5ca1d4c_0
  - npe2=0.7.8=pyhd8ed1ab_0
  - numba=0.61.2=py310h699fe88_0
  - numcodecs=0.13.1=py310h5eaa309_0
  - numpy=2.2.6=py310hefbff90_0
  - numpydoc=1.8.0=pyhd8ed1ab_1
  - ome-types=0.6.0=pyhd8ed1ab_0
  - ome-zarr=0.10.2=pyhd8ed1ab_0
  - omnipath=1.0.8=pyhd8ed1ab_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.9=he970967_0
  - openssl=3.5.2=h26f9b46_0
  - optree=0.15.0=py310h3788b33_0
  - orc=2.1.1=h2271f48_0
  - packaging=25.0=pyh29332c3_1
  - param=2.2.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=hc749103_2
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pims=0.7=pyhd8ed1ab_1
  - pint=0.24.4=pyhd8ed1ab_1
  - pip=25.1=pyh8b19718_0
  - pixman=0.46.0=h29eaf8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.7=pyh29332c3_0
  - pooch=1.8.2=pyhd8ed1ab_1
  - proj=9.6.0=h0054346_1
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - propcache=0.3.1=py310h89163eb_0
  - psutil=7.0.0=py310ha75aee5_0
  - psygnal=0.12.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=19.0.1=py310hff52083_0
  - pyarrow-core=19.0.1=py310h23ac199_0_cuda
  - pybind11=2.13.6=pyh1ec8472_2
  - pybind11-global=2.13.6=pyh415d2e4_2
  - pyconify=0.2.1=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pyct=0.5.0=pyhd8ed1ab_1
  - pydantic=2.11.3=pyh3cfb1c2_0
  - pydantic-compat=0.1.2=pyhd8ed1ab_0
  - pydantic-core=2.33.1=py310hc1293b2_0
  - pydantic-extra-types=2.10.5=pyh3cfb1c2_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyogrio=0.10.0=py310h0aed7a2_1
  - pyopengl=3.1.6=pyhd8ed1ab_2
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyproj=3.7.1=py310h71d0299_1
  - pyproject_hooks=1.2.0=pyhd8ed1ab_1
  - pyqtgraph=0.13.7=pyhd8ed1ab_1
  - pyside6=6.9.0=py310hfd10a26_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.17=hd6af730_0_cpython
  - python-build=1.2.2.post1=pyhff2d567_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-dotenv=1.1.0=pyh29332c3_1
  - python-igraph=0.11.8=py310h5996f03_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=7_cp310
  - pytorch=2.6.0=cuda126_generic_py310_h9bb2754_200
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.8.0=py310hf462985_0
  - pyyaml=6.0.2=py310h89163eb_2
  - pyzmq=26.4.0=py310h71f11fc_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.0=h6441bc3_1
  - qtconsole-base=5.6.1=pyha770c72_1
  - qtpy=2.4.3=pyhd8ed1ab_0
  - rav1e=0.6.6=he8a937b_2
  - rdma-core=57.0=h5888daf_0
  - re2=2024.07.02=h9925aae_2
  - readfcs=1.1.8=pyhd8ed1ab_0
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rich=14.0.0=pyh29332c3_0
  - rpds-py=0.24.0=py310hc1293b2_0
  - ruff=0.11.13=py310h31ffbac_0
  - s2n=1.5.14=h6c98b2b_0
  - scikit-image=0.25.2=py310h5eaa309_0
  - scipy=1.15.2=py310h1d65ade_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.1.0=pyhff2d567_0
  - shapely=2.1.0=py310h247727d_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.8=h1b44611_0
  - slicerator=1.1.0=pyhd8ed1ab_1
  - snappy=1.2.1=h8bd8927_1
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - spatial-image=1.1.0=pyhd8ed1ab_1
  - spatialdata=0.4.0=pyhd8ed1ab_0
  - spatialdata-io=0.2.0=pyhd8ed1ab_0
  - spatialdata-plot=0.2.10=pyhd8ed1ab_0
  - sphinx=8.1.3=pyhd8ed1ab_1
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - sqlite=3.49.1=h9eae976_2
  - squidpy=1.6.5=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - superqt=0.7.3=pyhb6d5dde_0
  - svt-av1=3.0.2=h5888daf_0
  - sympy=1.14.0=pyh2585a3b_105
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tbb=2022.1.0=h4ce085d_0
  - tblib=3.1.0=pyhd8ed1ab_0
  - texttable=1.7.0=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2025.3.30=pyhd8ed1ab_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.2.1=pyhd8ed1ab_1
  - tomli-w=1.2.0=pyhd8ed1ab_0
  - toolz=1.0.0=pyhd8ed1ab_1
  - toposort=1.10=pyhd8ed1ab_1
  - tornado=6.4.2=py310ha75aee5_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - triton=3.2.0=cuda126py310h50ec074_1
  - typeguard=4.4.2=pyhd8ed1ab_0
  - typer=0.15.3=pyhf21524f_0
  - typer-slim=0.15.3=pyh29332c3_0
  - typer-slim-standard=0.15.3=h1a15894_0
  - typing-inspection=0.4.0=pyhd8ed1ab_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py310ha75aee5_0
  - untokenize=0.1.1=pyhd8ed1ab_2
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.4.0=pyhd8ed1ab_0
  - validators=0.34.0=pyhd8ed1ab_1
  - vispy=0.14.3=py310h21d447c_1
  - wayland=1.23.1=h3e06ad9_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webencodings=0.5.1=pyhd8ed1ab_3
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.2=py310ha75aee5_0
  - xarray=2024.11.0=pyhd8ed1ab_0
  - xarray-dataclasses=1.9.1=pyhd8ed1ab_1
  - xarray-datatree=0.0.14=pyhd8ed1ab_0
  - xarray-schema=0.0.3=pyhd8ed1ab_0
  - xarray-spatial=0.4.0=pyhd8ed1ab_1
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xerces-c=3.2.5=h988505b_2
  - xkeyboard-config=2.44=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xsdata=24.3.1=pyhd8ed1ab_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.20.0=py310h89163eb_0
  - zarr=2.18.3=pyhd8ed1ab_1
  - zeromq=4.3.5=h3b0a872_7
  - zfp=1.0.1=h5888daf_2
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.4=h7955e40_0
  - zstandard=0.23.0=py310ha75aee5_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - adjusttext==1.3.0
      - aiofiles==24.1.0
      - anyio==4.9.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - array-api-compat==1.12.0
      - arrow==1.3.0
      - async-lru==2.0.5
      - blaze==0.10.1
      - bleach==6.2.0
      - blinker==1.9.0
      - cairocffi==1.7.1
      - cairosvg==2.8.2
      - celltypist==1.7.1
      - cssselect2==0.8.0
      - datashape==0.5.2
      - dcor==0.6
      - decoupler==2.1.0
      - defusedxml==0.7.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - fastjsonschema==2.21.1
      - flask==3.1.1
      - flask-cors==6.0.1
      - fonttools==4.59.1
      - fqdn==1.5.1
      - geographiclib==2.0
      - geopy==2.4.1
      - gprofiler-official==1.0.0
      - greenlet==3.2.4
      - gseapy==1.1.9
      - h11==0.16.0
      - h5py==3.14.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - joblib==1.5.1
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - legendkit==0.3.6
      - llvmlite==0.44.0
      - marsilea==0.5.3
      - matplotlib==3.10.5
      - matplotlib-venn==1.1.2
      - mistune==3.1.3
      - naivede==1.2.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - notebook==7.4.3
      - notebook-shim==0.2.4
      - numdifftools==0.9.41
      - nvidia-nccl-cu12==2.27.5
      - odo==0.5.0
      - openpyxl==3.1.5
      - overrides==7.7.0
      - pandas==2.3.1
      - pandocfilters==1.5.1
      - pillow==11.3.0
      - plotly==6.2.0
      - prometheus-client==0.22.1
      - ptitprince==0.2.7
      - pycairo==1.28.0
      - pypdl==1.5.4
      - pysodb==1.0.0
      - python-json-logger==3.3.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpy2==3.6.2
      - rpy2-rinterface==3.6.2
      - rpy2-robjects==3.6.1
      - scanpy==1.11.4
      - scikit-learn==1.7.1
      - scikit-misc==0.5.1
      - scikit-posthocs==0.11.4
      - send2trash==1.8.3
      - session-info2==0.2.1
      - sniffio==1.3.1
      - spanve==0.1.6
      - sparx==0.0.2
      - spatialde==1.1.3
      - sqlalchemy==2.0.43
      - statsmodels==0.14.5
      - terminado==0.18.1
      - types-python-dateutil==2.9.0.20250516
      - typing-extensions==4.14.1
      - tzlocal==5.3.1
      - umap-learn==0.5.9.post2
      - uri-template==1.3.0
      - webcolors==24.11.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - xgboost==3.0.2
prefix: /home/v16847mf/miniforge3/envs/biogis
