name: spartan-core
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=2.2.6
  - scipy=1.15.*
  - anndata=0.11.*
  - scanpy=1.11.*
  - squidpy=1.6.*
  - spatialdata=0.4.*
  - python-igraph=0.11.*
  - leidenalg=0.10.*
  - joblib=1.5.*
  - statsmodels=0.14.*
  - matplotlib=3.10.*
  - pip
